name: Stable release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: copy lib typescript files to base dir
      run: cp src/lib/others/ColorExtractor.ts .

    - name: Remove innecesary files and directories
      run: rm -rf .gitignore temp app docs resources src node_modules bin environment.js package.json package-lock.json styles.config tsconfig.json .github 
      
    - name: Check the output
      run: ls -lha .

    - name: Create a Release of commit
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ github.token }}
        automatic_release_tag: v1.0
        prerelease: false
        title: ColorExtractor - v1.0
        files: |
          LICENSE
          *.ts